### ISSUE TITLE
Bullseye 2022-04-07 default login changes

### ISSUE THREAD

**Issue by carlosperate** [carlosperate/rpi-os-custom-image#3]
The April 2022 release has removed the default `pi` username from Raspberry Pi OS:
https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/

This only seems to affect Bullseye and not Buster (legacy), or at least Buster 2022-04-07 is not affected.

Technically speaking, on first boot the "first-boot wizard" should jump and ask for a username and password, which could be automated with `expect`. However, with `dockerpi` the you end up in a step asking for username and password (maybe because the serial console is via tty?):

```
[  OK  ] Started Authorization Manager.

Raspbian GNU/Linux 11 raspberrypi ttyAMA0

raspberrypi login:
```

The workaround would be to add a `userconf`/`userconf.txt` file in the boot partition, with a username and password (more info in the link above).

To do that in automation the simplest thing might be to create a bash script and run it inside a docker container (mounting the image and script inside), as the intructions will be very much OS specific.

**Comment by potter-s** [comment]
I'm trying to automate creation of an image for a Pi B. The above was my thought for adding a user [back] in to the image. fdisk to find the sector start and then mount the linux partition, add the userconf file. Unless I'm doing something stupid, can't get this to work. Even copied an existing password from /etc/shadow.

**Comment by potter-s** [comment]
Brilliant idea, and good work though.

**Comment by carlosperate** [comment]
This has been added in https://github.com/carlosperate/rpi-os-custom-image/commit/0dba6c36f555339fa4927cbd167153bce12960b5.
